* Given a stock data, which has open and close prices for each trading day, we want to create an array of (n_samples, n_prices). 
> n_prices = 10

> n_samples = np.floor(stock_data's length/n_prices)

In [1]:
import pandas as pd
import numpy as np

dict_tickers = {
    'Apple': 'AAPL',
    'Microsoft': 'MSFT',
    'Google': 'GOOG',
    'Bitcoin': 'BTC-USD',
    'Facebook': 'FB'
}

In [2]:
def stockDataTransformer(filepath):
    df = pd.read_csv(filepath)
    df.set_index('Date', inplace=True)
    df1 = df[['Open', 'Close']].copy()
    data = df1.values
    n_samples = data.shape[0]//10*10
    reshape_number = data.shape[0]*data.shape[1]//10
    data1 = data[:n_samples].reshape((reshape_number, 10))
    return data1

In [14]:
tickerName = 'Apple'
filepath = f"raw-stock-data/{tickerName}.csv"
cols = [[f"open{i}", f"close{i}"] for i in range(1, 6)]

In [16]:
cols = [item for sublist in cols for item in sublist]
cols

['open1',
 'close1',
 'open2',
 'close2',
 'open3',
 'close3',
 'open4',
 'close4',
 'open5',
 'close5']

In [17]:
pd.DataFrame(stockDataTransformer(filepath), columns = cols)

,open1,close1,open2,close2,open3,close3,open4,close4,open5,close5
0,6.544805,6.562591,6.580681,6.573935,6.573936,6.469369,6.493286,6.457407,6.448822,6.500339
1,6.525484,6.442997,6.414786,6.369709,6.374307,6.459555,6.442995,6.422143,6.468141,6.314816
2,6.388414,6.594175,6.590189,6.492675,6.503406,6.380439,6.340882,6.063978,6.209944,6.227116
3,6.315432,6.315125,6.343028,6.374613,6.284153,6.111203,6.166093,5.889495,5.899002,5.971371
4,6.007556,6.006022,5.984863,6.109362,6.032700,5.889189,5.906976,5.993757,6.000809,5.952664
...,...,...,...,...,...,...,...,...,...,...
501,68.335998,69.041557,68.970034,69.177261,69.026757,69.011955,68.952758,69.081039,69.626246,68.937950
502,69.206854,70.062904,70.233134,70.129517,70.265201,71.520905,71.819405,71.493759,71.409881,71.918083
503,71.525832,72.443558,73.082501,74.096443,73.307008,73.376083,72.478106,73.960770,73.970641,73.612930
504,73.309478,74.797081,75.796216,76.385834,76.625131,76.558517,76.881705,78.194145,78.130000,77.138260
505,76.933521,76.807701,77.362767,77.769821,78.023925,78.630814,78.250892,78.097939,78.593807,78.376717